/**
 * GENERATED by tools/build-themes.py. Do not edit by hand.
 *
 * The picker's list, emitted from the same packs as themes.generated.css so
 * every option here has a stylesheet block to match.
 */
export interface ThemeChoice {
  id: string;
  label: string;
  dark: boolean;
}

export const THEMES: ThemeChoice[] = [
  { id: 'aurora-teal', label: "Glass Aurora \u2014 Teal", dark: true },
  { id: 'aurora-violet', label: "Glass Aurora \u2014 Violet", dark: true },
  { id: 'finance-ledger', label: "Finance Ledger", dark: false },
  { id: 'industrial-control-cyan', label: "Industrial \u2014 Control Room Cyan", dark: true },
  { id: 'industrial-day-cyan', label: "Industrial \u2014 Day Cyan", dark: false },
  { id: 'leather-night-tan', label: "Leather Journal \u2014 Night Tan", dark: true },
  { id: 'leather-parchment-tan', label: "Leather Journal \u2014 Parchment Tan", dark: false },
  { id: 'newsprint-night', label: "Newsprint \u2014 Night", dark: true },
  { id: 'nord-dark-frost', label: "Nord \u2014 Dark Frost", dark: true },
  { id: 'nord-light-frost', label: "Nord \u2014 Light Frost", dark: false },
];

export type ThemeId = (typeof THEMES)[number]['id'];

/**
 * The default. A dark theme, because the editor is the whole page and this
 * is the closest of the ten to the palette the app shipped with in 1.0.
 */
export const DEFAULT_THEME: ThemeId = 'nord-dark-frost';
